MAIN := sltx
OBJS := ast.cmo lexer.cmo parser.cmo eval.cmo main.cmo
MLS_WITHOUT_MLIS=main ast eval
MLS=$(MLS_WITHOUT_MLIS:=.ml)

%.cmo: %.ml
	ocamlc -c $<

%.cmi: %.mli
	ocamlc -c $<

$(MAIN): $(OBJS)
	ocamlc -o $@ $^

lexer.ml: lexer.mll
	ocamllex -q $<

parser.ml: parser.mly
	menhir $<

parser.mli: parser.mly
	menhir $<

clean:
	rm -f *.cmo *.cmi lexer.ml parser.ml parser.mli $(MAIN)

docs: 
	mkdir -p docs
	ocamlfind ocamldoc -I _build \
		-html -stars -d docs \
		-inv-merge-ml-mli -m A -hide-warnings $(MLS)

# Dependencies generated by `ocamldep -bytecode *.mli *.ml`.
ast.cmo :
eval.cmo : ast.cmo
lexer.cmo : parser.cmi
main.cmo : parser.cmi lexer.cmo eval.cmo
parser.cmo : ast.cmo parser.cmi
parser.cmi : ast.cmo
pprint.cmo : ast.cmo
